_wandb:
    value:
        cli_version: 0.21.0
        e:
            wr4qyfyovtfhggsk94njo9gl1dj8q2xa:
                args:
                    - --domain-groups
                    - '[["knee_x4","knee_x8"],["brain_x4", "brain_x8"]]'
                    - --config-paths
                    - configs/domain.yaml,configs/domain.yaml
                    - --epochs-per-block
                    - "5"
                    - --total-epochs
                    - "50"
                    - --wandb-project
                    - fastmri_domain_train
                codePath: domain_train.py
                codePathLocal: domain_train.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "982818799616"
                        used: "645327826944"
                email: swpants05@snu.ac.kr
                executable: /home/swpants05/.pyenv/versions/3.11.4/bin/python
                git:
                    commit: 4ab2ce6a4d77e7fd8e8e4a44d972f0378c880540
                    remote: git@github.com:sawo0150/2025_GeekSeek.git
                gpu: NVIDIA GeForce RTX 4070 SUPER
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 7168
                      memoryTotal: "12878610432"
                      name: NVIDIA GeForce RTX 4070 SUPER
                      uuid: GPU-15ce3daf-aa6f-fd1c-9624-e83615081790
                host: swpants05-desktop
                memory:
                    total: "67340546048"
                os: Linux-6.8.0-60-generic-x86_64-with-glibc2.35
                program: /home/swpants05/Desktop/2025_FastMri/2025_GeekSeek/domain_train.py
                python: CPython 3.11.4
                root: /home/swpants05/Desktop/2025_FastMri/2025_GeekSeek
                startedAt: "2025-07-17T11:28:12.211438Z"
                writerId: wr4qyfyovtfhggsk94njo9gl1dj8q2xa
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 1
                - 41
                - 50
            "2":
                - 1
                - 41
                - 50
            "3":
                - 13
                - 16
            "4": 3.11.4
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
GPU_NUM:
    value: 0
LRscheduler:
    value:
        _target_: torch.optim.lr_scheduler.ExponentialLR
        gamma: 0.97
LossFunction:
    value:
        _target_: utils.common.loss_function.SSIML1Loss
        k1: 0.01
        k2: 0.03
        mask_only: true
        mask_threshold:
            brain_x4: 5e-05
            brain_x8: 5e-05
            knee_x4: 2e-05
            knee_x8: 2e-05
        region_weight: false
        weight_l1: 1
        weight_ssim: 1
        win_size: 7
aug:
    value:
        _target_: utils.augmentations.mraugmenter.MRAugmenter
        aug_delay: 5
        aug_exp_decay: 6
        aug_on: true
        aug_schedule_mode: epoch
        aug_schedule_type: ramp
        aug_strength: 0.6
        max_epochs: 5
        max_rotation_angle: 15
        max_shear_angle: 10
        scale_range:
            - 0.85
            - 1.15
        shift_extent: 5
        val_loss_grad_plateau: -0.001
        val_loss_grad_start: -0.05
        val_loss_window_size: 5
        weight_dict:
            fliph: 0.5
            flipv: 0.5
            rotate: 0.25
            scale: 0.5
            shear: 0.5
            shift: 0.2
batch_size:
    value: 1
centerCropPadding:
    value:
        _target_: utils.data.transforms.KspaceCenterCropPad
        target_size:
            - 384
            - 384
collator:
    value:
        _target_: utils.data.collator.IdentityCollator
compressor:
    value:
        _target_: utils.data.coil_compression.SCCCompressor
        num_calib_lines: 24
        target_coils: auto
corner_size:
    value: 16
crop_size:
    value:
        - 384
        - 384
data:
    value:
        PROJECT_ROOT: /home/swpants05/Desktop/2025_FastMri/
        data_path_eval: /home/swpants05/Desktop/2025_FastMri/Data/leaderboard/
        data_path_train: /home/swpants05/Desktop/2025_FastMri/Data/train/
        data_path_val: /home/swpants05/Desktop/2025_FastMri/Data/val/
        domain_filter:
            - knee_x4
            - knee_x8
        mask_thresholds:
            brain_x4: 5e-05
            brain_x8: 5e-05
            knee_x4: 2e-05
            knee_x8: 2e-05
        repo_ROOT: /home/swpants05/Desktop/2025_FastMri/2025_GeekSeek/
early_stop:
    value:
        enable: false
        stages:
            - epoch: 10
              ssim: 0.9
            - epoch: 20
              ssim: 0.95
            - epoch: 25
              ssim: 0.96
evaluation:
    value:
        evaluation:
            batch_size: 5
            enable: true
            every_n_epochs: 1
            leaderboard_root: /home/swpants05/Desktop/2025_FastMri/Data/leaderboard/
            output_key: reconstruction
exp_name:
    value: domain0_knee_x4_knee_x8
input_key:
    value: kspace
lr:
    value: 0.001
maskAugment:
    value:
        _target_: utils.augmentations.maskaugmenter.MaskAugmenter
        allow_any_combination: true
        aug_delay: 5
        aug_exp_decay: 6
        aug_on: true
        aug_schedule_mode: epoch
        aug_schedule_type: ramp
        aug_strength: 0.6
        enable: true
        mask_specs:
            equispaced:
                accel:
                    - 4
                    - 8
                cf:
                    - 0.07
                    - 0.1
                prob: 0.4
            equispaced_fraction:
                accel:
                    - 4
                    - 8
                cf:
                    - 0.07
                    - 0.1
                prob: 0.3
            magic_fraction:
                accel:
                    - 4
                    - 8
                cf:
                    - 0.07
                    - 0.1
                prob: 0.1
            random:
                accel:
                    - 4
                    - 8
                cf:
                    - 0.07
                    - 0.1
                prob: 0.2
        max_epochs: 5
        val_loss_grad_plateau: -0.001
        val_loss_grad_start: -0.05
        val_loss_window_size: 5
maskDuplicate:
    value:
        _target_: utils.data.duplicate_dataset.DuplicateMaskDataset
        accel_cfgs:
            - accel: 4
            - accel: 8
        bundle_path: /home/swpants05/Desktop/2025_FastMri/2025_GeekSeek//metaData/precomputed_masks.npz
        enable: true
max_key:
    value: max
model:
    value:
        _target_: utils.model.varnet.VarNet
        chans: 18
        num_cascades: 18
        sens_chans: 8
num_epochs:
    value: 5
num_workers:
    value: 4
optimizer:
    value:
        _target_: torch.optim.NAdam
        betas:
            - 0.9
            - 0.999
        lr: 0.001
        momentum_decay: 0.004
        weight_decay: 0
report_interval:
    value: 500
sampler:
    value:
        _target_: utils.data.sampler.GroupByCoilBatchSampler
seed:
    value: 430
target_key:
    value: image_label
training:
    value:
        accum_steps: 2
        amp: true
        checkpointing: true
        deepspeed:
            config:
                dist_init_required: false
                fp16:
                    enabled: false
                optimizer:
                    params:
                        betas:
                            - 0.9
                            - 0.999
                        eps: 1e-08
                        lr: 0.001
                        weight_decay: 0
                    type: Adam
                scheduler:
                    params:
                        cos_min_ratio: 0.1
                        total_num_steps: null
                        warmup_min_ratio: 0.001
                        warmup_num_steps: null
                    type: WarmupCosineLR
                train_micro_batch_size_per_gpu: 1
                zero_optimization:
                    offload_optimizer:
                        device: cpu
                    stage: 1
            enable: false
use_crop:
    value: false
val_batch_size:
    value: 5
wandb:
    value:
        entity: swpants05-seoul-national-university
        max_vis_per_cat: 5
        project: fastmri_domain_train
        use_receptiveField: false
        use_visLogging: true
        use_wandb: true
warmup_epochs:
    value: 3
