# configs/optim/adabelief.yaml
# pip install adabelief-pytorch
_target_: adabelief_pytorch.AdaBelief
lr: 1e-3
betas: [0.9, 0.999]
eps: 1e-16             # 작은 eps로 더 정밀한 분산 추정
weight_decay: 0.0
amsgrad: false
