# configs/optimizer/lamb.yaml
_target_: torch_optimizer.Lamb  # ✅ 올바른 경로
lr: 1e-3
betas: [0.9, 0.999]
eps: 1e-6
weight_decay: 0.01
clamp_value: 10.0               # torch_optimizer.Lamb 에서는 유효
adam: false
debias: false
