# ── 확률적 경사하강법(기본) ──────────────────────────────────────
_target_: torch.optim.SGD
lr: 1e-3               # 학습률
momentum: 0.9          # 모멘텀 계수 (0이면 모멘텀 미사용)
weight_decay: 0.0      # L2 정규화 강도
nesterov: false        # 네스테로프 모멘텀 사용 여부