_wandb:
    value:
        cli_version: 0.21.0
        e:
            ydludw7woev40c76stcumdrsi6bfohy2:
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "982818799616"
                        used: "621342203904"
                email: swpants05@snu.ac.kr
                executable: /home/swpants05/.pyenv/versions/3.11.4/bin/python3
                git:
                    commit: 70d60cdfd9b8e832e853234abd6a22f85b8e524b
                    remote: git@github.com:sawo0150/2025_GeekSeek.git
                gpu: NVIDIA GeForce RTX 4070 SUPER
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 7168
                      memoryTotal: "12878610432"
                      name: NVIDIA GeForce RTX 4070 SUPER
                      uuid: GPU-15ce3daf-aa6f-fd1c-9624-e83615081790
                host: swpants05-desktop
                memory:
                    total: "67340554240"
                os: Linux-6.8.0-60-generic-x86_64-with-glibc2.35
                program: /home/swpants05/Desktop/2025_FastMri/2025_GeekSeek/main.py
                python: CPython 3.11.4
                root: /home/swpants05/Desktop/2025_FastMri/2025_GeekSeek
                startedAt: "2025-07-07T09:40:11.899908Z"
                writerId: ydludw7woev40c76stcumdrsi6bfohy2
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 1
                - 41
                - 50
            "2":
                - 1
                - 41
                - 50
            "3":
                - 13
                - 16
            "4": 3.11.4
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
GPU_NUM:
    value: 0
LRscheduler:
    value:
        _target_: torch.optim.lr_scheduler.CosineAnnealingLR
        T_max: 1
        eta_min: 1e-06
LossFunction:
    value:
        _target_: utils.common.loss_function.L1Loss
        mask_only: false
        mask_threshold:
            brain_x4: 5e-05
            brain_x8: 5e-05
            knee_x4: 2e-05
            knee_x8: 2e-05
        region_weight: false
batch_size:
    value: 1
data:
    value:
        PROJECT_ROOT: /home/swpants05/Desktop/2025_FastMri/
        data_path_train: /home/swpants05/Desktop/2025_FastMri/Data/train/
        data_path_val: /home/swpants05/Desktop/2025_FastMri/Data/val/
        mask_thresholds:
            brain_x4: 5e-05
            brain_x8: 5e-05
            knee_x4: 2e-05
            knee_x8: 2e-05
exp_name:
    value: small_varnet_resume_test
input_key:
    value: kspace
lr:
    value: 0.001
max_key:
    value: max
model:
    value:
        cascade: 1
        chans: 9
        net_name: varnet_small
        sens_chans: 4
num_epochs:
    value: 1
optimizer:
    value:
        _target_: torch.optim.AdamW
        betas:
            - 0.9
            - 0.999
        eps: 1e-08
        lr: 0.001
        weight_decay: 0.01
report_interval:
    value: 500
seed:
    value: 430
target_key:
    value: image_label
training:
    value:
        accum_steps: 1
        amp: false
        checkpointing: false
wandb:
    value:
        entity: swpants05-seoul-national-university
        max_vis_per_cat: 5
        project: fastmri-2025
        use_wandb: true
