_wandb:
    value:
        cli_version: 0.21.0
        e:
            7p4eawskb658112y4yklw3mxskkopjc6:
                args:
                    - --domain-groups
                    - '[["knee_x4","knee_x8"],["brain_x4", "brain_x8"]]'
                    - --config-paths
                    - configs/domain.yaml,configs/domain.yaml
                    - --epochs-per-block
                    - "5"
                    - --total-epochs
                    - "50"
                    - --wandb-project
                    - fastmri_domain_train
                codePath: domain_train.py
                codePathLocal: domain_train.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "982818799616"
                        used: "645328515072"
                email: swpants05@snu.ac.kr
                executable: /home/swpants05/.pyenv/versions/3.11.4/bin/python
                git:
                    commit: 4ab2ce6a4d77e7fd8e8e4a44d972f0378c880540
                    remote: git@github.com:sawo0150/2025_GeekSeek.git
                gpu: NVIDIA GeForce RTX 4070 SUPER
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 7168
                      memoryTotal: "12878610432"
                      name: NVIDIA GeForce RTX 4070 SUPER
                      uuid: GPU-15ce3daf-aa6f-fd1c-9624-e83615081790
                host: swpants05-desktop
                memory:
                    total: "67340546048"
                os: Linux-6.8.0-60-generic-x86_64-with-glibc2.35
                program: /home/swpants05/Desktop/2025_FastMri/2025_GeekSeek/domain_train.py
                python: CPython 3.11.4
                root: /home/swpants05/Desktop/2025_FastMri/2025_GeekSeek
                startedAt: "2025-07-17T11:13:03.746732Z"
                writerId: 7p4eawskb658112y4yklw3mxskkopjc6
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 1
                - 41
                - 50
            "2":
                - 1
                - 41
                - 50
            "3":
                - 13
                - 16
            "4": 3.11.4
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
GPU_NUM:
    value: 0
batch_size:
    value: 1
corner_size:
    value: 16
crop_size:
    value:
        - 384
        - 384
data:
    value:
        domain_filter:
            - knee_x4
            - knee_x8
defaults:
    value:
        - _self_
        - model: varnet_sweep2
        - data: local_sangwonDesktop
        - LRscheduler: ExponentialLR
        - LossFunction: SSIM+L1
        - training: base_sw
        - early_stop: none
        - evaluation: leaderboard
        - optimizer: nadam
        - aug: mraugment
        - centerCropPadding: crop_kspace
        - maskDuplicate: none
        - maskAugment: universal
        - collator: identity
        - compressor: scc
        - sampler: grouping
exp_name:
    value: domain0_knee_x4_knee_x8
input_key:
    value: kspace
lr:
    value: 0.001
max_key:
    value: max
num_epochs:
    value: 5
num_workers:
    value: 4
report_interval:
    value: 500
seed:
    value: 430
target_key:
    value: image_label
use_crop:
    value: false
val_batch_size:
    value: 5
wandb:
    value:
        entity: swpants05-seoul-national-university
        max_vis_per_cat: 5
        name: domain0_knee_x4_knee_x8_e0-5
        project: fastmri_domain_train
        use_receptiveField: false
        use_visLogging: true
        use_wandb: true
warmup_epochs:
    value: 3
