_wandb:
    value:
        cli_version: 0.21.0
        e:
            bzq2eydet9xfopq3c7eanla3adgqd1az:
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "982818799616"
                        used: "676745068544"
                email: swpants05@snu.ac.kr
                executable: /home/swpants05/miniconda3/envs/fmri/bin/python3
                git:
                    commit: 07a838c55183b2184302e00cb1eefdb1b873db88
                    remote: git@github.com:sawo0150/2025_GeekSeek.git
                gpu: NVIDIA GeForce RTX 4070 SUPER
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 7168
                      memoryTotal: "12878610432"
                      name: NVIDIA GeForce RTX 4070 SUPER
                      uuid: GPU-15ce3daf-aa6f-fd1c-9624-e83615081790
                host: swpants05-desktop
                memory:
                    total: "67340537856"
                os: Linux-6.8.0-64-generic-x86_64-with-glibc2.35
                program: /home/swpants05/Desktop/2025_FastMri/2025_GeekSeek/main.py
                python: CPython 3.13.5
                root: /home/swpants05/Desktop/2025_FastMri/2025_GeekSeek
                startedAt: "2025-07-26T04:25:49.618999Z"
                writerId: bzq2eydet9xfopq3c7eanla3adgqd1az
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 41
                - 50
            "2":
                - 1
                - 41
                - 50
            "3":
                - 13
                - 16
            "4": 3.13.5
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
GPU_NUM:
    value: 0
LRscheduler:
    value:
        _target_: torch.optim.lr_scheduler.ExponentialLR
        gamma: 0.96
LossFunction:
    value:
        _target_: utils.common.loss_function.SSIML1Loss
        k1: 0.01
        k2: 0.03
        mask_only: true
        mask_threshold:
            brain_x4: 5e-05
            brain_x8: 5e-05
            knee_x4: 2e-05
            knee_x8: 2e-05
        region_weight: false
        weight_l1: 1
        weight_ssim: 1
        win_size: 7
aug:
    value:
        _target_: utils.augmentations.mraugmenter.MRAugmenter
        aug_delay: 5
        aug_exp_decay: 6
        aug_on: true
        aug_schedule_mode: epoch
        aug_schedule_type: ramp
        aug_strength: 0.7
        max_epochs: 30
        max_rotation_angle: 15
        max_shear_angle: 10
        scale_range:
            - 0.85
            - 1.15
        shift_extent: 5
        val_loss_grad_plateau: -0.001
        val_loss_grad_start: -0.05
        val_loss_window_size: 5
        weight_dict:
            fliph: 0.5
            flipv: 0.5
            rotate: 0.25
            scale: 0.5
            shear: 0.5
            shift: 0.2
batch_size:
    value: 1
centerCropPadding:
    value:
        _target_: utils.data.transforms.KspaceCenterCropPad
        target_size:
            - 384
            - 384
collator:
    value:
        _target_: utils.data.collator.IdentityCollator
compressor:
    value:
        _target_: utils.data.coil_compression.SCCCompressor
        num_calib_lines: 24
        target_coils: auto
corner_size:
    value: 16
crop_size:
    value:
        - 384
        - 384
data:
    value:
        PROJECT_ROOT: /home/swpants05/Desktop/2025_FastMri/
        data_path_eval: /home/swpants05/Desktop/2025_FastMri/Data/leaderboard/
        data_path_train: /home/swpants05/Desktop/2025_FastMri/Data/train/
        data_path_val: /home/swpants05/Desktop/2025_FastMri/Data/val/
        mask_thresholds:
            brain_x4: 5e-05
            brain_x8: 5e-05
            knee_x4: 2e-05
            knee_x8: 2e-05
        repo_ROOT: /home/swpants05/Desktop/2025_FastMri/2025_GeekSeek/
early_stop:
    value:
        enable: false
        stages:
            - epoch: 10
              ssim: 0.9
            - epoch: 20
              ssim: 0.95
            - epoch: 25
              ssim: 0.96
evaluation:
    value:
        evaluation:
            batch_size: 1
            enable: true
            every_n_epochs: 1
            leaderboard_root: /home/swpants05/Desktop/2025_FastMri/Data/leaderboard/
            output_key: reconstruction
exp_name:
    value: fivarnet_test
input_key:
    value: kspace
lr:
    value: 0.001
maskAugment:
    value:
        _target_: utils.augmentations.maskaugmenter.MaskAugmenter
        allow_any_combination: true
        aug_delay: 5
        aug_exp_decay: 6
        aug_on: true
        aug_schedule_mode: epoch
        aug_schedule_type: ramp
        aug_strength: 0.7
        enable: true
        mask_specs:
            equispaced:
                accel:
                    - 4
                    - 8
                cf:
                    - 0.07
                    - 0.1
                prob: 0.4
            equispaced_fraction:
                accel:
                    - 4
                    - 8
                cf:
                    - 0.07
                    - 0.1
                prob: 0.3
            magic_fraction:
                accel:
                    - 4
                    - 8
                cf:
                    - 0.07
                    - 0.1
                prob: 0.1
            random:
                accel:
                    - 4
                    - 8
                cf:
                    - 0.07
                    - 0.1
                prob: 0.2
        max_epochs: 30
        val_loss_grad_plateau: -0.001
        val_loss_grad_start: -0.05
        val_loss_window_size: 5
maskDuplicate:
    value:
        _target_: utils.data.duplicate_dataset.DuplicateMaskDataset
        accel_cfgs:
            - accel: 4
            - accel: 8
        bundle_path: /home/swpants05/Desktop/2025_FastMri/2025_GeekSeek//metaData/precomputed_masks.npz
        enable: true
max_epochs:
    value: 30
max_key:
    value: max
model:
    value:
        _target_: utils.model.feature_varnet.FlexibleCascadeVarNet
        cascade_counts:
            - 2
            - 4
            - 6
        crop_size: none
        feature_chans: 9
        kspace_mult_factor: 1e+06
        mask_center: true
        pools: 4
        sens_chans: 8
        sens_pools: 4
        unet_chans: 32
        variant: dlka
num_epochs:
    value: 30
num_workers:
    value: 0
optimizer:
    value:
        _target_: torch.optim.NAdam
        betas:
            - 0.9
            - 0.999
        lr: 0.001
        momentum_decay: 0.004
        weight_decay: 0
report_interval:
    value: 5000
sampler:
    value:
        _target_: utils.data.sampler.GroupByCoilBatchSampler
seed:
    value: 430
target_key:
    value: image_label
training:
    value:
        accum_steps: 10
        amp: true
        checkpointing: false
        deepspeed:
            config:
                dist_init_required: false
                fp16:
                    enabled: false
                optimizer:
                    params:
                        betas:
                            - 0.9
                            - 0.999
                        eps: 1e-08
                        lr: 0.001
                        weight_decay: 0
                    type: Adam
                scheduler:
                    params:
                        cos_min_ratio: 0.1
                        total_num_steps: null
                        warmup_min_ratio: 0.001
                        warmup_num_steps: null
                    type: WarmupCosineLR
                train_micro_batch_size_per_gpu: 1
                zero_optimization:
                    offload_optimizer:
                        device: cpu
                    stage: 1
            enable: false
        grad_accum_scheduler:
            enable: true
            milestones:
                - epoch: 0
                  steps: 2
                - epoch: 5
                  steps: 10
                - epoch: 25
                  steps: 16
        grad_clip:
            enable: true
            max_norm: 1
            norm_type: 2
use_crop:
    value: false
val_batch_size:
    value: 1
wandb:
    value:
        entity: swpants05-seoul-national-university
        max_vis_per_cat: 5
        project: AMP_sweep
        use_receptiveField: false
        use_visLogging: true
        use_wandb: true
warmup_epochs:
    value: 3
