class SliceData(Dataset):
    def __init__(self, root, transform, input_key, target_key, is_train=False, forward=False, classifier=None):
        self.transform = transform
        self.input_key = input_key
        self.target_key = target_key
        self.is_train = is_train
        self.forward = forward
        self.classifier = classifier
