_wandb:
    value:
        cli_version: 0.21.0
        e:
            g4gh95jotkz4371aq3x7svwfc1azaqhw:
                args:
                    - --checkpoint
                    - /home/swpants05/Desktop/2025_FastMri/result/small_varnet_resume_test/checkpoints/model.pt
                    - --override_epochs
                    - "2"
                codePath: resume_main.py
                codePathLocal: resume_main.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "982818799616"
                        used: "619696730112"
                email: swpants05@snu.ac.kr
                executable: /home/swpants05/.pyenv/versions/3.11.4/bin/python3
                git:
                    commit: 13c0188cf0bdd4dcac293b1fa47b5728b73d5747
                    remote: git@github.com:sawo0150/2025_GeekSeek.git
                gpu: NVIDIA GeForce RTX 4070 SUPER
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 7168
                      memoryTotal: "12878610432"
                      name: NVIDIA GeForce RTX 4070 SUPER
                      uuid: GPU-15ce3daf-aa6f-fd1c-9624-e83615081790
                host: swpants05-desktop
                memory:
                    total: "67340546048"
                os: Linux-6.8.0-60-generic-x86_64-with-glibc2.35
                program: /home/swpants05/Desktop/2025_FastMri/2025_GeekSeek/resume_main.py
                python: CPython 3.11.4
                root: /home/swpants05/Desktop/2025_FastMri/2025_GeekSeek
                startedAt: "2025-07-06T16:17:35.573337Z"
                writerId: g4gh95jotkz4371aq3x7svwfc1azaqhw
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 1
                - 41
                - 50
            "2":
                - 1
                - 41
                - 50
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.4
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
GPU_NUM:
    value: 0
LRscheduler:
    value:
        _target_: torch.optim.lr_scheduler.CosineAnnealingLR
        T_max: 1
        eta_min: 1e-06
LRscheduler__target_:
    value: torch.optim.lr_scheduler.CosineAnnealingLR
LRscheduler_T_max:
    value: 1
LRscheduler_eta_min:
    value: 1e-06
LossFunction:
    value:
        _target_: utils.common.loss_function.SSIMLoss
LossFunction__target_:
    value: utils.common.loss_function.SSIMLoss
PROJECT_ROOT:
    value: /home/swpants05/Desktop/2025_FastMri/
batch_size:
    value: 1
cascade:
    value: 1
chans:
    value: 9
data:
    value:
        PROJECT_ROOT: /home/swpants05/Desktop/2025_FastMri/
        data_path_train: /home/swpants05/Desktop/2025_FastMri/Data/train/
        data_path_val: /home/swpants05/Desktop/2025_FastMri/Data/val/
data_path_train:
    value: /home/swpants05/Desktop/2025_FastMri/Data/train
data_path_val:
    value: /home/swpants05/Desktop/2025_FastMri/Data/val
exp_dir:
    value: /home/swpants05/Desktop/2025_FastMri/result/small_varnet_resume_test/checkpoints
exp_name:
    value: small_varnet_resume_test
input_key:
    value: kspace
lr:
    value: 0.001
main_dir:
    value: /home/swpants05/Desktop/2025_FastMri/result/small_varnet_resume_test/main.py
max_key:
    value: max
max_vis_per_cat:
    value: 5
model:
    value:
        cascade: 1
        chans: 9
        net_name: varnet_small
        sens_chans: 4
net_name:
    value: varnet_small
num_epochs:
    value: 2
optimizer:
    value:
        _target_: adabelief_pytorch.AdaBelief
        amsgrad: false
        betas:
            - 0.9
            - 0.999
        eps: 1e-16
        lr: 0.001
        weight_decay: 0
optimizer__target_:
    value: adabelief_pytorch.AdaBelief
optimizer_amsgrad:
    value: false
optimizer_betas:
    value:
        - 0.9
        - 0.999
optimizer_eps:
    value: 1e-16
optimizer_lr:
    value: 0.001
optimizer_weight_decay:
    value: 0
report_interval:
    value: 500
resume_checkpoint:
    value: /home/swpants05/Desktop/2025_FastMri/result/small_varnet_resume_test/checkpoints/model.pt
seed:
    value: 430
sens_chans:
    value: 4
target_key:
    value: image_label
training_accum_steps:
    value: 1
training_amp:
    value: false
training_checkpointing:
    value: false
use_wandb:
    value: true
val_dir:
    value: /home/swpants05/Desktop/2025_FastMri/result/small_varnet_resume_test/reconstructions_val
val_loss_dir:
    value: /home/swpants05/Desktop/2025_FastMri/result/small_varnet_resume_test
wandb_entity:
    value: swpants05-seoul-national-university
wandb_max_vis_per_cat:
    value: 5
wandb_project:
    value: fastmri-2025
wandb_use_wandb:
    value: true
