_target_: utils.model.feature_varnet.AttentionFeatureVarNet_n_sh_w
num_cascades: 10
chans: 9
pools: 4
sens_chans: 8
sens_pools: 4
acceleration: 4
mask_center: true
kspace_mult_factor: 1e6
use_checkpoint: true
