
# configs/model/prompt_fivarnet.yaml
_target_: utils.model.feature_varnet.prompt_fivarnet.PromptFIVarNet

num_cascades: 10      # Feature Space Cascade의 수 (기존 PromptFIVarNet과 동일)
num_image_cascades: 10  # [NEW] Image Space Cascade의 수 (새로 추가)
chans: 9
pools: 4
sens_chans: 8
sens_pools: 4
mask_center: true


# --- Prompt-FIVarNet 전용 파라미터 ---
num_domains: 2          # knee, brain
domain_embed_dim: 64    # 도메인 프롬프트 벡터 차원
num_acc: 2              # 가속도 종류 (x4, x8)
acc_embed_dim: 64       # 가속도 프롬프트 벡터 차원
use_checkpoint: true    # 체크포인팅 활성화 여부


