_target_: utils.augmentations.mraugmentater.MRAugmenter

# MRAugmenter.__init__ 에 전달될 파라미터들
aug_on: true
aug_delay: 10
max_epochs: ${num_epochs}      # train.yaml의 num_epochs 값을 그대로 가져와 사용
aug_strength: 0.9
aug_schedule: 'ramp'        # 'constant', 'ramp', 'exp' 중 선택
aug_exp_decay: 6.0

# 각 증강 기법의 적용 가중치 (0.0 ~ 1.0)
weight_dict:
  fliph: 0.5
  flipv: 0.5
  rotate: 1.0
  scale: 1.0

# 회전 및 스케일 관련 하이퍼파라미터
max_rotation_angle: 15.0
scale_range: [0.85, 1.15]