enable: true
_target_: utils.data.duplicate_dataset.DuplicateMaskDataset

# 복제할 가속도 목록
accel_cfgs:
  - {accel: 4}
  - {accel: 8}

# 📍 절대경로  ──  train.yaml 의 repo_ROOT 를 그대로 참조
bundle_path: ${data.repo_ROOT}/metaData/precomputed_masks.npz
