# configs/train_promptmr.yaml
defaults:
  - _self_
  - model: prompt_fivarnet       # 프롬프트 모델 기본 설정
  - data: local_gpu  # 데이터 경로 설정
  - classifier: cnn             # 분류기 모델 설정
  - LRscheduler: ExponentialLR
  - LossFunction: SSIM+L1
  - training: base
  - early_stop: none
  - evaluation: leaderboard
  - optimizer: nadam
  - aug: mraugment
  - centerCropPadding: crop_kspace
  - maskDuplicate: acc4_acc8
  - maskAugment: universal
  - collator: identity
  - compressor: none # SCC/GCC는 현재 PromptVarNet과 호환성 작업 필요
  - sampler: grouping


# === Data Preprocessing === -  Mask → Crop → Compress → Tensor
use_crop: false                  # spatial crop 사용 여부
crop_size: [384, 384]           # crop 할 (H, W) - 무조건 짝수로 지정
corner_size : 16

# === Classifier 학습 설정 ===
classifier_training:
  epochs: 1
  lr: 1e-4
  batch_size: 1

# === 공통 학습 하이퍼파라미터 ===
GPU_NUM: 0
batch_size: 1
val_batch_size: 3
num_epochs: 30
max_epochs: 30
warmup_epochs : 3
lr: 1e-3
report_interval: 100
seed: 430
num_workers: 6

exp_name : prompt-varnet-final

input_key:  kspace
target_key: image_label
max_key:    max

wandb:
  project: PromptMR_Project
  entity: swpants05-seoul-national-university
  use_wandb: true
  max_vis_per_cat: 5
  use_visLogging: true
  use_receptiveField: false
