defaults:
  - _self_
  - model: varnet_small   # 모델 설정
  - data: local_sangwonDesktop           # 데이터 경로 설정
  - LRscheduler: CosineAnnealingLR        # ⬅️  추가 - https://gaussian37.github.io/dl-pytorch-lr_scheduler/참고
  - LossFunction: L1Loss
  - training: base
  - optimizer: adamw          # ⬅️ 새로 추가  
  - aug: mraugment    # ⬅️ 새로 추가
  - compress: gcc  # ⬅️ 새로 추가
  
# === 공통 학습 하이퍼파라미터 ===
GPU_NUM: 0
batch_size: 1
num_epochs: 1
lr: 1e-3
report_interval: 500
seed: 430

exp_name : small_varnet_resume_test

# these three are *required* by utils/data/load_data.py → create_data_loaders
input_key:  kspace
target_key: image_label
max_key:    max

wandb:
  project: fastmri-2025
  entity: swpants05-seoul-national-university        # W&B 팀/계정
  use_wandb: true           # false 이면 모든 wandb 로그 함수가 noop
  max_vis_per_cat: 5        # epoch 마다 카테고리별 이미지 수 (0 → 안 올림)
