defaults:
  - model: varnet_small   # 모델 설정
  - data: local           # 데이터 경로 설정

# === 공통 학습 하이퍼파라미터 ===
GPU_NUM: 0
batch_size: 1
num_epochs: 5
lr: 1e-3
report_interval: 500
seed: 430

wandb:
  project: fastmri-2025
  entity: your_team        # W&B 팀/계정
